
version: '2'

services:

  zookeeper0:
    container_name: zookeeper0
    hostname: zookeeper0
    image: hyperledger/fabric-zookeeper:0.4.22
    restart: always
    environment:
      - ZOO_MY_ID=1
      - ZOO_SERVERS=server.1=zookeeper0:2878:3878 server.2=zookeeper1:2879:3879 server.3=zookeeper2:2880:3880
    ports:
      - "2171:2181"
      - "2878:2878"
      - "3878:3878"
    volumes: # 挂载数据
      - /usr/local/zookeeper-cluster/node1/data:/data
      - /usr/local/zookeeper-cluster/node1/datalog:/datalog
      - /usr/local/zookeeper-cluster/node1/logs:/logs



  zookeeper1:
    container_name: zookeeper1
    hostname: zookeeper1
    image: hyperledger/fabric-zookeeper:0.4.22
    restart: always
    environment:
      - ZOO_MY_ID=2
      - ZOO_SERVERS=server.1=zookeeper0:2878:3878 server.2=zookeeper1:2879:3879 server.3=zookeeper2:2880:3880
    ports:
      - "2172:2181"
      - "2879:2879"
      - "3879:3879"
    volumes: # 挂载数据
      - /usr/local/zookeeper-cluster/node2/data:/data
      - /usr/local/zookeeper-cluster/node2/datalog:/datalog
      - /usr/local/zookeeper-cluster/node2/logs:/logs

  zookeeper2:
    container_name: zookeeper2
    hostname: zookeeper2
    image: hyperledger/fabric-zookeeper:0.4.22
    restart: always
    environment:
      - ZOO_MY_ID=3
      - ZOO_SERVERS=server.1=zookeeper0:2878:3878 server.2=zookeeper1:2879:3879 server.3=zookeeper2:2880:3880
    ports:
      - "2173:2181"
      - "2880:2880"
      - "3880:3880"
    volumes: # 挂载数据
      - /usr/local/zookeeper-cluster/node3/data:/data
      - /usr/local/zookeeper-cluster/node3/datalog:/datalog
      - /usr/local/zookeeper-cluster/node3/logs:/logs


  kafka0:
    container_name: kafka0
    hostname: kafka0
    image: hyperledger/fabric-kafka:0.4.22
    restart: always
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ADVERTISED_HOST_NAME:kafka0
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka0:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_LOG_RETENTION_MS=-1
    ports:
      - "9092:9092"
    volumes:
      - /usr/local/kafka-cluster/node1/logs:/kafka
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2


  kafka1:
    container_name: kafka1
    hostname: kafka1
    image: hyperledger/fabric-kafka:0.4.22
    restart: always
    environment:
      - KAFKA_BROKER_ID=2
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ADVERTISED_HOST_NAME:kafka1
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka1:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_LOG_RETENTION_MS=-1
    ports:
      - "9093:9092"
    volumes:
      - /usr/local/kafka-cluster/node2/logs:/kafka
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2

  kafka2:
    container_name: kafka2
    hostname: kafka2
    image: hyperledger/fabric-kafka:0.4.22
    restart: always
    environment:
      - KAFKA_BROKER_ID=3
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ADVERTISED_HOST_NAME:kafka2
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka2:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_LOG_RETENTION_MS=-1
    ports:
      - "9094:9092"
    volumes:
      - /usr/local/kafka-cluster/node3/logs:/kafka
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2



  kafka3:
    container_name: kafka3
    image: hyperledger/fabric-kafka:0.4.22
    restart: always
    environment:
      - KAFKA_BROKER_ID=4
      - KAFKA_MIN_INSYNC_REPLICAS=2
      - KAFKA_DEFAULT_REPLICATION_FACTOR=3
      - KAFKA_ADVERTISED_PORT=9092
      - KAFKA_ADVERTISED_HOST_NAME:kafka3
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka3:9092
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper0:2181,zookeeper1:2181,zookeeper2:2181
      - KAFKA_MESSAGE_MAX_BYTES=103809024
      - KAFKA_REPLICA_FETCH_MAX_BYTES=103809024
      - KAFKA_UNCLEAN_LEADER_ELECTION_ENABLE=false
      - KAFKA_LOG_RETENTION_MS=-1
    ports:
      - "9095:9092"
    volumes:
      - /usr/local/kafka-cluster/node4/logs:/kafka
    depends_on:
      - zookeeper0
      - zookeeper1
      - zookeeper2